dist: trusty
sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
    
before_script:
  - curl -fsSL get.nextflow.io | bash && mv nextflow $HOME/bin

script:
  - ./ci/ci.sh run && ./ci/ci.sh validate
